apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-0806-05-app
  namespace: rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/test-0806-05/overlays/development
    repoURL: https://github.com/jdubrick-ai/test-0806-05-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
